apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediator-pod-patcher
  namespace: remediator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediator-binding
  namespace: remediator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remediator-pod-patcher
subjects:
- kind: ServiceAccount
  name: remediator-sa
  namespace: remediator
